<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CarritoDeCompras.aspx.cs" Inherits="Vistas.Articulos.CarritoDeCompras" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 166px;
        }
        .auto-style3 {
            width: 166px;
            height: 26px;
        }
        .auto-style5 {
            text-align: center;
            width: 773px;
        }
        .auto-style6 {
            width: 773px;
        }
        .auto-style7 {
            width: 773px;
        }
        .auto-style8{
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style2">
                        <asp:HyperLink ID="hlnkInicio" runat="server" NavigateUrl="~/Inicio.aspx">Volver  al Menú Principal</asp:HyperLink>
                    </td>
                    <td class="auto-style5" >
                        <asp:Label ID="lblTitulo" runat="server" Text="Carrito de Compras" Font-Bold="True" Font-Size="XX-Large"></asp:Label>
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3"><asp:HyperLink ID="hlnkComprarArticulos" runat="server" NavigateUrl="~/Articulos/CompraArticulo.aspx">Artículos</asp:HyperLink>
                        </td>
                    <td class="auto-style5">
                    &nbsp;<br />
                        <asp:Label ID="lblMensaje" runat="server" Font-Bold="True" Font-Italic="False" Text="Aún no tiene artículos agregados" Visible="False"></asp:Label>
                    </td>
                    <td class="auto-style8">
                        <asp:Label ID="lblA" runat="server" Font-Bold="True" Font-Size="Large" Text="Artículos:"></asp:Label>
                        <asp:Label ID="lblCantArticulos" runat="server">0</asp:Label>
                    </td>
                </tr>
                 <tr>
                    <td class="auto-style3"></td>
                    <td class="auto-style7">
                    <asp:GridView ID="gvCarritoDeCompras" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" OnPageIndexChanging="gvCarritoDeCompras_PageIndexChanging" OnRowDeleting="gvCarritoDeCompras_RowDeleting" >
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:TemplateField HeaderText="Articulo">
                                <ItemTemplate>
                                    <asp:Label ID="lbl_it_Articulo" runat="server" Text='<%# Eval("Articulos.Nombre") %>'></asp:Label>
                                    <asp:Label ID="lbl_it_IdArticulo" runat="server" Visible="False"></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="PrecioUnitario" HeaderText="Precio Unitario" />
                            <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                        <br />
                     </td>
                     <td class="auto-style8">
                        <asp:Label ID="lblT" runat="server" Font-Bold="True" Font-Size="Large" Text="Total:"></asp:Label>
                         <asp:Label ID="lblTotal" runat="server">$0.00</asp:Label>
                        </td>
                </tr>
                 <tr>
                    <td class="auto-style3"></td>
                    <td rowspan="1" class="auto-style6">
                        &nbsp;</td>
                     <td class="auto-style8">
                        <asp:Button ID="btnComprar" runat="server" Text="Comprar" OnClick="btnComprar_Click" />
                     </td>
                </tr>
                 <tr>
                    <td class="auto-style3"></td>
                    <td class="auto-style5">
                        <asp:Button ID="btnEliminarTodo" runat="server" Text="Eliminar Todo" OnClick="btnEliminarTodo_Click" />
                     </td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>