<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListarProveedores.aspx.cs" Inherits="Vistas.Admin.Proveedores.ListarProveedores" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            font-size: xx-large;
        }
        .auto-style3 {
            font-size: x-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <table class="auto-style1">
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2"><strong>Proveedores</strong></td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td class="auto-style3"><strong>Filtros de Búsqueda</strong></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td rowspan="8">
                        <asp:GridView ID="gvProveedores" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" BackColor="White" BorderColor="#DEDFDE" BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="IDProveedor" ForeColor="Black" GridLines="Vertical" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="IDProveedor" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="IDProveedor" />
                                <asp:BoundField DataField="NombreProveedor" HeaderText="Nombre" SortExpression="NombreProveedor" />
                                <asp:BoundField DataField="Telefono" HeaderText="Telefono" SortExpression="Telefono" />
                                <asp:BoundField DataField="EMail" HeaderText="Email" SortExpression="EMail" />
                                <asp:BoundField DataField="Direccion" HeaderText="Direccion" SortExpression="Direccion" />
                                <asp:BoundField DataField="NombreCiudad" HeaderText="Ciudad" SortExpression="NombreCiudad" />
                                <asp:CheckBoxField DataField="Estado" HeaderText="Estado" SortExpression="Estado" />
                            </Columns>
                            <EmptyDataTemplate>
                                <strong><em>No proveedores realizadas con los criterios de búsqueda propuestos</em></strong>
                            </EmptyDataTemplate>
                            <FooterStyle BackColor="#CCCC99" />
                            <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                            <RowStyle BackColor="#F7F7DE" />
                            <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#FBFBF2" />
                            <SortedAscendingHeaderStyle BackColor="#848384" />
                            <SortedDescendingCellStyle BackColor="#EAEAD3" />
                            <SortedDescendingHeaderStyle BackColor="#575357" />
                        </asp:GridView>
                    </td>
                    <td><strong>ID Proveedor</strong></td>
                </tr>
                <tr>
                    <td>
                        <asp:TextBox ID="txtIdProveedor" runat="server"></asp:TextBox>
                        <asp:CompareValidator runat="server" ControlToValidate="txtIdProveedor" Operator="GreaterThan" Type="Integer" ValueToCompare="0"></asp:CompareValidator>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td><strong>Nombre</strong></td>
                </tr>
                <tr>
                    <td>
                        <asp:TextBox ID="txtNombreProveedor" runat="server"></asp:TextBox>
                        <asp:RegularExpressionValidator runat="server" ControlToValidate="txtNombreProveedor" ValidationExpression="^(?:[A-Za-z0-9]+\s*)*$"></asp:RegularExpressionValidator>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:Button ID="btnFiltrar" runat="server" OnClick="btnFiltrar_Click" Text="Filtrar" />
                    </td>
                </tr>
                <tr>
                    <td>
                        &nbsp;</td>
                </tr>
            </table>

        </div>
    </form>
</body>
</html>
